### ISSUE TITLE
高度超过一行的弹幕会与其它弹幕重叠

### ISSUE THREAD

**Issue by ouuan** [dd-center/DDatElectron#18]
高度超过一行的弹幕会与其它弹幕重叠，如果是最上面一行的话显示不全。

![image](https://user-images.githubusercontent.com/30581822/82626678-fd3df400-9c1a-11ea-8a4d-0467f599f648.png)

是 c66fff9c1ded2c4a70ecbfd268dfe209b04dc4c1 引入的问题。

**Comment by ouuan** [comment]
```diff
diff --git a/index.html b/index.html
index 8420aa2..aed7089 100644
--- a/index.html
+++ b/index.html
@@ -35,12 +35,13 @@
       padding-top: 0;
       height: calc(100vh - 200px);
       min-height: 300px;
-      overflow-y: auto;
+      overflow: auto;
+      white-space: nowrap;
     }
 
     .danmakuContainer {
       position: relative;
-      overflow-y: hidden;
+      overflow: visible;
     }
 
     .danmakuDetectors {

```

如上修改效果如下：

![image](https://user-images.githubusercontent.com/30581822/82626799-4beb8e00-9c1b-11ea-9980-bd4deb452f43.png)

![image](https://user-images.githubusercontent.com/30581822/82626847-66be0280-9c1b-11ea-8c93-20fe776176d3.png)

最后有两个黑点不知道是什么，还没仔细看..

因为不知道有没有更好的解决方法，就不开 PR 了。

**Comment by ouuan** [comment]
差点忘了，我上面那个修改有个严重的问题，水平滚动条拖不动..怀疑是 Vue 的原因，但我不太了解，也还没去研究。

**Comment by simon300000** [comment]
🔥Simon🔥

**Comment by simon300000** [comment]
> 差点忘了，我上面那个修改有个严重的问题，水平滚动条拖不动..怀疑是 Vue 的原因，但我不太了解，也还没去研究。

是IntersectionObserver，弹幕那里有几个看不见，宽度为0的隐身细长喷火龙，用来判断用户垂直滚动，滚走了就把看不见弹幕藏起来
所以横过来滚的话，因为宽度为0，就是在看得见的看不见之间反复横跳了

**Comment by ouuan** [comment]
![image](https://user-images.githubusercontent.com/30581822/82678041-8422b900-9c7b-11ea-8f67-d20faba0a064.png)

![image](https://user-images.githubusercontent.com/30581822/82678258-dcf25180-9c7b-11ea-880d-0dd0d810900c.png)

我这首行显示不全，而且水平滚动条需要把竖直滚动条拉下去才能看见（也就是水平滚动条在内层）。

**Comment by simon300000** [comment]
啊 我看看

**Comment by simon300000** [comment]
显示弹幕的地方是一个单独的区域，有自己的水平/垂直滚动条，我这里好像没什么问题？

**Comment by ouuan** [comment]
> 显示弹幕的地方是一个单独的区域，有自己的水平/垂直滚动条

没太懂..是没有我上面说的情况（首行显示不全，而且水平滚动条需要把竖直滚动条拉下去才能看见，也就是水平滚动条在内层）吗？

> 我这里好像没什么问题

我这边的环境是 Manjaro Linux, KDE, node v14.2.0, [package-lock.json](https://github.com/dd-center/DDatElectron/files/4674631/package-lock.txt)（GitHub 不支持上传 json 就改成 txt 了）, commit 是最新的也就是 1ac6f1748cf4d10857a90c9218e76aab097e95f4。

![系统字体](https://user-images.githubusercontent.com/30581822/82767797-bb9c8b80-9e5c-11ea-9328-f1cd02b86927.png)

**Comment by simon300000** [comment]
嗯，macOS没有首行显示不全的问题
<img width="912" alt="image" src="https://user-images.githubusercontent.com/12656264/82770337-79615300-9e38-11ea-83ee-ce3ff8840f6c.png">

还有就是滚动条，这块区域应该有3个滚动条，一个整个页面的竖直滚动条，一个弹幕区域的竖直滚动条，一个弹幕区域的水平滚动条

不过水平滚动条和垂直滚动条不在同一个区域，这个我的确需要好好看看，我刚刚也注意到了

**Comment by simon300000** [comment]
我又用你的办法修了一次，这次大概好了吧www

**Comment by ouuan** [comment]
现在基本上没有问题了。

有个小问题是最下面有个空白部分，不过不影响使用。

![image](https://user-images.githubusercontent.com/30581822/82772133-da0c8200-9e70-11ea-96ac-0f99adbece8f.png)

**Comment by simon300000** [comment]
太好啦
