### ISSUE TITLE
没有Android端

### ISSUE THREAD

**Issue by Neteraxe** [dd-center/DDatElectron#27]
感觉可能是个大坑wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
开发者为什么会时间这么余裕

**Comment by simon300000** [comment]
我时间不是很充裕（
有一个别人写的Flutter端，不过我还没有仔细看过
https://github.com/dd-center/DDatFlutter

**Comment by Neteraxe** [comment]
本来其实想帮忙的，但是一看就有点心虚，所以赶紧close了
开发者虽说时间不充裕，可比我要优秀多了:)
既然这样，我也会关注DDatFlutter工程得，虽然也是入门不久

**Comment by simon300000** [comment]
哇哈哈

**Comment by simon300000** [comment]
还有一个开发很活跃的vtubermusic网站，有兴趣的话也可以看看（
https://github.com/vtbmusic

**Comment by Neteraxe** [comment]
看了DDatFlutter，感觉什么都没有，可改的地方很多，只有一个启动贴图:)，下周有时间试一试帮一下忙吧，是不是有一个api文件要看?

**Comment by Neteraxe** [comment]
可以做外部协作者吗?

**Comment by simon300000** [comment]
可以啊，想弄哪个repo？

**Comment by Neteraxe** [comment]
就是fork的DDatFlutter，那个觉得有很多可改的

**Comment by Neteraxe** [comment]
没有权限:)
git push flutter master
ERROR: Permission to dd-center/DDatFlutter.git denied to Neteraxe.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by simon300000** [comment]
要到这里接受一下
https://github.com/dd-center/DDatFlutter/invitations
