### ISSUE TITLE
过多的并发连接数引起网络瘫痪

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [dd-center/DDatElectron#77]
![image](https://user-images.githubusercontent.com/44915585/95881211-ee630400-0daa-11eb-9b89-eabe9e341fd8.png)
![image](https://user-images.githubusercontent.com/44915585/95881240-f91d9900-0daa-11eb-82fc-14f1d07fa85a.png)
1.12版本下，同时监听直播间数量过高，堵塞了宽带的出口，导致整条宽带下所有的设备都无法访问任何的网络资源

**Comment by simon300000** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/12656264/95892697-307a4e80-0d87-11eb-9253-d93a708c0747.png">
这里这个设置也没用吗？

**Comment by SaltyFishOnTheSea** [comment]
![image](https://user-images.githubusercontent.com/44915585/95925439-58e86400-0dec-11eb-85af-3cd381bf30f5.png)
默认设置没改动过，但是3000对于家庭宽带太高了，建议改到1000，我这300M移动宽带超过1500就基本没法用了

**Comment by simon300000** [comment]
唔 那为啥不改呢 可以写一个1000什么的小一点的数字

这个应该不会导致宽带不足吧… 不应该会有很大的流量呀

**Comment by SaltyFishOnTheSea** [comment]
家用宽带会限制最高出口连接数，连接数到达一定值之后就不再允许该条宽带继续建立新的连接了，现在改到了500，基本不会堵塞我的出口了

**Comment by simon300000** [comment]
会不会是路由器不好啊 哈哈
我家里没有这个限制，中国移动

**Comment by simon300000** [comment]
修好了就好ww

**Comment by simon300000** [comment]
如果要限制tcp连接数的话，那要对每个tcp包进行解码，感觉不太可能…
