### ISSUE TITLE
Possible More details in ReadMe?

### ISSUE THREAD

**Issue by KKKKKyle** [dd-center/DDatElectron#8]
先膜拜下...技术力太高了以至于没能完全理解这个项目。凭借一点点还没大学毕业的cs知识..是把其他项目需要用的requests当做任务，分配到各个client上？主要占用网络资源？

**Comment by simon300000** [comment]
主要去看看 https://github.com/dd-center/Cluster-center 吧，大多数信息都在那个repo
前几天有点忙，没回复抱歉

**Comment by simon300000** [comment]
基本上全是vtbs.moe的需要，然后转发到这里来当任务做了，的确都属于网络任务www

**Comment by KKKKKyle** [comment]
哦哦好的好的。BTW好像1.7.4版的windows端的重启更新键没有用？

**Comment by simon300000** [comment]
哎呀，我去看看怎么回事

**Comment by simon300000** [comment]
我这里根本不能下载，应该是因为https://github.com/electron-userland/electron-builder/issues/4744 的原因
